language: cpp
dist: bionic
os:
 - linux

script:
 - mkdir build && cd build
 - cmake ..
 - make -j10
 - ./example/generate_image QR_CODE QRCodeTestText test.png
 - ./example/scan_image test.png
 - ./test/blackbox/ReaderTest ../test/samples
 - ./test/blackbox/WriterTest
 - ./test/blackbox/ReaderTest *.png
 - cd ..
 - mkdir build-unit && cd build-unit
 - cmake ../test/unit
 - make -j10
 - ./ZXingUnitTest
 
